---
title: "626 Midterm 1"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(glmnet)
library(caret)
library(tidyverse)
library(pROC)
```

## Import Data
```{r}
training_data = read.table("Data/training_data.txt", header = T)
test_data = read.table("Data/test_data.txt", header = T)

# Creating binary & multi category activity code
training_data = training_data %>% mutate(activity_bin = case_when(activity >= 4 ~ 0, TRUE ~ 1),
                                         activity_multi = case_when(activity >= 7 ~ 7, TRUE ~ as.numeric(activity))) %>% 
  select(subject, activity, activity_bin, activity_multi, everything())
set.seed(2023)
```

## Training and Test Data set
```{r}
## Split test and train 
idx = round(nrow(training_data)*0.2, digits=0) # round to integer number of index
test.idx = sample(1:nrow(training_data), idx) # random select idx from all index
data.train = training_data[-test.idx,] # 80% training data
data.test = training_data[test.idx,] # 20% testing data
X.train = data.train %>% select(F1:F561) %>% as.matrix()
Y.train.bin = data.train %>% select(activity_bin) %>% as.matrix() %>% as.factor()
Y.train.multi = data.train %>% select(activity_multi) %>% as.matrix() %>% as.factor()
X.test = data.test %>% select(F1:F561) %>% as.matrix()
Y.test.bin = data.test %>% select(activity_bin) %>% as.matrix() %>% as.factor()
Y.test.multi = data.test %>% select(activity_multi) %>% as.matrix() %>% as.factor()
```


## Task 1: Lasso Logistic Regression
```{r}
cv.lasso = cv.glmnet(X.train, Y.train.bin, alpha = 1, family = "binomial", type.measure = "class") # Lasso: alpha = 1 
lasso.model = glmnet(X.train, Y.train.bin, alpha = 1, family = "binomial", lambda = cv.lasso$lambda.min)
lasso.res = predict(lasso.model, X.test, type="class") %>% as.factor()
lasso.prob = predict(lasso.model, X.test, type="response")
lasso.accuracy = confusionMatrix(data = lasso.res, reference = Y.test.bin)
task1.res = predict(lasso.model, as.matrix(test_data[, -1]), type = "class")
# write.table(data.frame(as.integer(task1.res)), file = "binary_A4786.txt", row.names = FALSE, col.names = FALSE)
```

## Task 1 Evaluation: Table and Figures
```{r}
knitr::kable(lasso.accuracy$table)
pROC::roc(as.numeric(Y.test.bin) ~ as.numeric(lasso.prob), plot = TRUE, print.auc = TRUE)
```

## Task 2: kNN
```{r}
X.train.selected = X.train[, which(lasso.model$beta != 0)]
X.test.selected = X.test[, which(lasso.model$beta != 0)]
trControl = trainControl(method = "cv", number = 10)
knn.task2 = train(X.train.selected, as.factor(Y.train.multi),
                  method = "knn",
                  trControl  = trControl)
knn.task2.res = predict(knn.task2, X.test.selected, type="raw")
knn.accuracy = confusionMatrix(data = knn.task2.res, reference = Y.test.multi)
```

## Task 2: Bagged Decision Tree
```{r}

BaggedTree = train(X.train.selected, as.factor(Y.train.multi),
                   method = "treebag",
                   trControl  = trControl)
BaggedTree.res = predict(BaggedTree, X.test.selected)
bagged.accuracy = confusionMatrix(data = BaggedTree.res, reference = Y.test.multi)
task2.res = predict(BaggedTree, as.matrix(test_data[, which(lasso.model$beta != 0)+1]), type="raw") %>% as.factor()
# write.table(data.frame(as.integer(task2.res)), file = "multiclass_A4786.txt", row.names = FALSE, col.names = FALSE)
```


## Task 2 Evaluation: Table and Figures
```{r}
knitr::kable(knn.accuracy$table)
knitr::kable(bagged.accuracy$table)
bagged.accuracy
```












